![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

<img src="https://user-images.githubusercontent.com/7065401/68501079-0695df00-023c-11ea-841f-455dac84a089.jpg"
    style="width:400px; float: right; margin: 0 40px 40px 40px;"></img>

# Reading CSV and TXT files

Rather than creating `Series` or `DataFrames` strutures from scratch, or even from Python core sequences or `ndarrays`, the most typical use of **pandas** is based on the loading of information from files or sources of information for further exploration, transformation and analysis.

In this lecture we'll learn how to read comma-separated values files (.csv) and raw text files (.txt) into pandas `DataFrame`s.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [2]:
import pandas as pd
import csv

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Reading data with Python

As we saw on previous courses we can read data simply using Python.

When you want to work with a file, the first thing to do is to open it. This is done by invoking the `open()` built-in function.

`open()` has a single required argument that is the path to the file and has a single return, the file object.

The `with` statement automatically takes care of closing the file once it leaves the `with` block, even in cases of error.

In [12]:
filepath = 'btc-market-price.csv'

with open(filepath, 'r') as reader:
    print(reader)

<_io.TextIOWrapper name='btc-market-price.csv' mode='r' encoding='utf-8'>

Once the file is opened, we can read its content as follows:

In [24]:
filepath = 'btc-market-price.csv'

with open(filepath, 'r') as reader:
    for index, line in enumerate(reader.readlines()):
        # read just the first 10 lines
        if (index < 10):
            timestamp, price = line.split(',')
            print(f"{timestamp}: ${price}")

2/4/17 0:00: $1099.169125

3/4/17 0:00: $1141.813

4/4/17 0:00: $?

5/4/17 0:00: $1133.079314

6/4/17 0:00: $-

7/4/17 0:00: $-

8/4/17 0:00: $1181.149838

9/4/17 0:00: $1208.8005

10/4/17 0:00: $1207.744875

11/4/17 0:00: $1226.617038

In [31]:
with open('exam_review.csv', 'r') as fp:
  reader = csv.reader(fp, delimiter = '>')
  next(reader)
  for index, values in enumerate(reader):
      if not values:
        continue
      fname, lname, age, math, french = values
      print(f"{fname} {lname} (age {age}) got {math} in Math and {french} in French")

Ray Morley (age 18) got 68,000 in Math and 75,000 in French
Melvin Scott (age 24) got 77 in Math and 83 in French
Amirah Haley (age 22) got 92 in Math and 67 in French
Gerard Mills (age 19) got 78,000 in Math and 72 in French
Amy Grimes (age 23) got 91 in Math and 81 in French

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Reading data with Pandas

Probably one of the most recurrent types of work for data analysis: public data sources, logs, historical information tables, exports from databases. So the pandas library offers us functions to read and write files in multiple formats like CSV, JSON, XML and Excel's XLSX, all of them creating a `DataFrame` with the information read from the file.

We'll learn how to read different type of data including:
- CSV files (.csv)
- Raw text files (.txt)
- JSON data from a file and from an API
- Data from a SQL query over a database

There are many other available reading functions as the following table shows:

![pandas read data table](https://user-images.githubusercontent.com/7065401/68400151-51d5c200-0156-11ea-9732-aa00400c8e4b.png)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## The `read_csv` method

The first method we'll learn is **read_csv**, that let us read comma-separated values (CSV) files and raw text (TXT) files into a `DataFrame`.

The `read_csv` function is extremely powerful and you can specify a very broad set of parameters at import time that allow us to accurately configure how the data will be read and parsed by specifying the correct structure, enconding and other details. The most common parameters are as follows:

- `filepath`: Path of the file to be read.
- `sep`: Character(s) that are used as a field separator in the file.
- `header`: Index of the row containing the names of the columns (None if none).
- `index_col`: Index of the column or sequence of indexes that should be used as index of rows of the data.
- `names`: Sequence containing the names of the columns (used together with header = None).
- `skiprows`: Number of rows or sequence of row indexes to ignore in the load.
- `na_values`: Sequence of values that, if found in the file, should be treated as NaN.
- `dtype`: Dictionary in which the keys will be column names and the values will be types of NumPy to which their content must be converted.
- `parse_dates`: Flag that indicates if Python should try to parse data with a format similar to dates as dates. You can enter a list of column names that must be joined for the parsing as a date.
- `date_parser`: Function to use to try to parse dates.
- `nrows`: Number of rows to read from the beginning of the file.
- `skip_footer`: Number of rows to ignore at the end of the file.
- `encoding`: Encoding to be expected from the file read.
- `squeeze`: Flag that indicates that if the data read only contains one column the result is a Series instead of a DataFrame.
- `thousands`: Character to use to detect the thousands separator.
- `decimal`: Character to use to detect the decimal separator.
- `skip_blank_lines`: Flag that indicates whether blank lines should be ignored.

> Full `read_csv` documentation can be found here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html.

In this case we'll try to read our `btc-market-price.csv` CSV file using different parameters to parse it correctly.

This file contains records of the mean price of Bitcoin per date.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Reading our first CSV file

Everytime we call `read_csv` method, we'll need to pass an explicit `filepath` parameter indicating the path where our CSV file is.

Any valid string path is acceptable. The string could be a URL. Valid URL schemes include HTTP, FTP, S3, and file. For file URLs, a host is expected. A local file could be: `file://localhost/path/to/table.csv`.

For example we can use `read_csv` method to load data directly from an URL:

In [3]:
csv_url = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"

hp = pd.read_csv(csv_url)
hp.to_csv('salam.csv')

Or just use a local file:

In [9]:
df = pd.read_csv('btc-market-price.csv', header = None)

df.head()

                     0            1
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

In this case we let pandas infer everything related to our data, but in most of the cases we'll need to explicitly tell pandas how we want our data to be loaded. To do that we use parameters.

Let's see how theses parameters work.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## First row behaviour with `header` parameter

The CSV file we're reading has only two columns: `Timestamp` and `Price`. It doesn't have a header. Pandas automatically assigned the first row of data as headers, which is incorrect. We can overwrite this behavior with the `header` parameter.

In [12]:
df = pd.read_csv('btc-market-price.csv', header = None)
df

                       0            1
0    2017-04-02 00:00:00  1099.169125
1    2017-04-03 00:00:00  1141.813000
2    2017-04-04 00:00:00  1141.600363
3    2017-04-05 00:00:00  1133.079314
4    2017-04-06 00:00:00  1196.307937
..                   ...          ...
360  2018-03-28 00:00:00  7960.380000
361  2018-03-29 00:00:00  7172.280000
362  2018-03-30 00:00:00  6882.531667
363  2018-03-31 00:00:00  6935.480000
364  2018-04-01 00:00:00  6794.105000

[365 rows x 2 columns]

In [ ]:
df.head()

             0            1
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00     1141.813
2  4/4/17 0:00            ?
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00            -

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Missing values with `na_values` parameter

We can define a `na_values` parameter with the values we want to be recognized as NA/NaN. In this case empty strings `''`, `?` and `-` will be recognized as null values.

In [11]:
df = pd.read_csv('btc-market-price.csv', header = None, na_values = ['', '?', '-'])
df

                       0            1
0    2017-04-02 00:00:00  1099.169125
1    2017-04-03 00:00:00  1141.813000
2    2017-04-04 00:00:00  1141.600363
3    2017-04-05 00:00:00  1133.079314
4    2017-04-06 00:00:00  1196.307937
..                   ...          ...
360  2018-03-28 00:00:00  7960.380000
361  2018-03-29 00:00:00  7172.280000
362  2018-03-30 00:00:00  6882.531667
363  2018-03-31 00:00:00  6935.480000
364  2018-04-01 00:00:00  6794.105000

[365 rows x 2 columns]

In [13]:
df.head()

                     0            1
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Column names using `names` parameter

We'll add that columns names using the `names` parameter.

In [49]:
df = pd.read_csv('btc-market-price.csv', header = None, na_values = ['', '?', '-'], names = ['Timestamp','Price'])
df

        Timestamp        Price
0     2/4/17 0:00  1099.169125
1     3/4/17 0:00  1141.813000
2     4/4/17 0:00          NaN
3     5/4/17 0:00  1133.079314
4     6/4/17 0:00          NaN
..            ...          ...
360  28/3/18 0:00  7960.380000
361  29/3/18 0:00  7172.280000
362  30/3/18 0:00  6882.531667
363  31/3/18 0:00  6935.480000
364   1/4/18 0:00  6794.105000

[365 rows x 2 columns]

In [50]:
df.head()

     Timestamp        Price
0  2/4/17 0:00  1099.169125
1  3/4/17 0:00  1141.813000
2  4/4/17 0:00          NaN
3  5/4/17 0:00  1133.079314
4  6/4/17 0:00          NaN

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Column types using `dtype` parameter


Without using the `dtype` parameter pandas will try to figure it out the type of each column automatically. We can use `dtype` parameter to force pandas to use certain dtype.

In this case we'll force the `Price` column to be `float`.

In [17]:
df = pd.read_csv('btc-market-price.csv', header = None, na_values = ['','-','?'], names = ['Timestamp', 'Price'], dtype={'Price':'float64'})
df['Price'] = df['Price'].fillna(0).astype(int)
df['Price'].dtype

dtype('int64')

In [60]:
df.head()

     Timestamp  Price
0  2/4/17 0:00   1099
1  3/4/17 0:00   1141
2  4/4/17 0:00      0
3  5/4/17 0:00   1133
4  6/4/17 0:00      0

In [15]:
df.dtypes

0     object
1    float64
dtype: object

The `Timestamp` column was interpreted as a regular string (`object` in pandas notation), we can parse it manually using a vectorized operation as we saw on previous courses.

We'll parse `Timestamp` column to `Datetime` objects using `to_datetime` method:

In [18]:
pd.to_datetime(df['Timestamp']).head()

0   2017-04-02
1   2017-04-03
2   2017-04-04
3   2017-04-05
4   2017-04-06
Name: Timestamp, dtype: datetime64[ns]

In [19]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [20]:
df.head()

   Timestamp  Price
0 2017-04-02   1099
1 2017-04-03   1141
2 2017-04-04   1141
3 2017-04-05   1133
4 2017-04-06   1196

In [23]:
df.dtypes

Timestamp    datetime64[ns]
Price                 int64
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Date parser using `parse_dates` parameter

Another way of dealing with `Datetime` objects is using `parse_dates` parameter with the position of the columns with dates.

In [ ]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'},
                 parse_dates=[0])

In [ ]:
df.head()

   Timestamp        Price
0 2017-02-04  1099.169125
1 2017-03-04  1141.813000
2 2017-04-04          NaN
3 2017-05-04  1133.079314
4 2017-06-04          NaN

In [ ]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Adding index to our data using `index_col` parameter

By default, pandas will automatically assign a numeric autoincremental index or row label starting with zero. You may want to leave the default index as such if your data doesn’t have a column with unique values that can serve as a better index. In case there is a column that you feel would serve as a better index, you can override the default behavior by setting `index_col` property to a column. It takes a numeric value representing the index or a string of the column name for setting a single column as index or a list of numeric values or strings for creating a multi-index.

In our data, we are choosing the first column, `Timestamp`, as index (index=0) by passing zero to the `index_col` argument.

In [28]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'},
                 parse_dates=[0],
                 index_col=[1])

In [29]:
df.head()

             Timestamp
Price
1099.169125 2017-04-02
1141.813000 2017-04-03
1141.600363 2017-04-04
1133.079314 2017-04-05
1196.307937 2017-04-06

In [ ]:
df.dtypes

Price    float64
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## A more challenging parsing

Now we'll read another CSV file. This file has the following columns:

- `first_name`
- `last_name`
- `age`
- `math_score`
- `french_score`
- `next_test_date`

Let's read it and see how it looks like.

In [31]:
exam_df = pd.read_csv('exam_review.csv', sep = '>')

In [32]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Custom data delimiters using `sep` parameter

We can define which delimiter to use by using the `sep` parameter. If we don't use the `sep` parameter, pandas will automatically detect the separator.

In most of the CSV files separator will be comma (`,`) and will be automatically detected. But we can find files with other separators like semicolon (`;`), tabs (`\t`, specially on TSV files), whitespaces or any other special character.

In this case the separator is a `>` character.

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>')

In [ ]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Custom data encoding

Files are stored using different "encodings". You've probably heard about ASCII, UTF-8, latin1, etc.

While reading data custom encoding can be defined with the `encoding` parameter.

- `encoding='UTF-8'`: will be used if data is UTF-8 encoded.
- `encoding='iso-8859-1'`: will be used if data is ISO/IEC 8859-1 ("extended ASCII") encoded.

In our case we don't need a custom enconding as data is properly loaded.

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Custom numeric `decimal` and `thousands` character  

The decimal and thousands characters could change between datasets. If we have a column containing a comma (`,`) to indicate the decimal or thousands place, then this column would be considered a string and not numeric.

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>')

In [ ]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [34]:
exam_df[['math_score', 'french_score']].dtypes

math_score      object
french_score    object
dtype: object

To solve that, ensuring such columns are interpreted as integer values, we'll need to use the `decimal` and/or `thousands` parameters to indicate correct decimal and/or thousands indicators.

In [45]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
)

In [47]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [ ]:
exam_df[['math_score', 'french_score']].dtypes

math_score      float64
french_score    float64
dtype: object

Let's see what happens with the `thousands` parameter:

In [48]:
pd.read_csv('exam_review.csv',
            sep='>',
            thousands=',')

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18       68000         75000
1     Melvin     Scott   24          77            83
2     Amirah     Haley   22          92            67
3     Gerard     Mills   19       78000            72
4        Amy    Grimes   23          91            81

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Excluding specific rows

We can use the `skiprows` to:

- Exclude reading specified number of rows from the beginning of a file, by passing an integer argument. **This removes the header too**.
- Skip reading specific row indices from a file, by passing a list containing row indices to skip.

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',')

In [ ]:
exam_df

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18        68.0          75.0
1     Melvin     Scott   24        77.0          83.0
2     Amirah     Haley   22        92.0          67.0
3     Gerard     Mills   19        78.0          72.0
4        Amy    Grimes   23        91.0          81.0

To skip reading the first 2 rows from this file, we can use `skiprows=2`:

In [50]:
pd.read_csv('exam_review.csv',
            sep='>',
            skiprows=2,
            header = None)

        0       1   2       3   4
0  Melvin   Scott  24      77  83
1  Amirah   Haley  22      92  67
2  Gerard   Mills  19  78,000  72
3     Amy  Grimes  23      91  81

As the header is considered as the first row, to skip reading data rows 1 and 3, we can use `skiprows=[1,3]`:

In [ ]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',',
                      skiprows=[1,3])

In [ ]:
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Get rid of blank lines

The `skip_blank_lines` parameter is set to `True` so blank lines are skipped while we read files.

If we set this parameter to `False`, then every blank line will be loaded with `NaN` values into the `DataFrame`.

In [53]:
pd.read_csv('exam_review.csv',
            sep='>',
            skip_blank_lines=False)

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Loading specific columns

We can use the `usecols` parameter when we want to load just specific columns and not all of them.

Performance wise, it is better because instead of loading an entire dataframe into memory and then deleting the not required columns, we can select the columns that we’ll need, while loading the dataset itself.

As a parameter to `usecols`, you can pass either a list of strings corresponding to the column names or a list of integers corresponding to column index.

In [ ]:
pd.read_csv('exam_review.csv',
            usecols=['first_name', 'last_name', 'age'],
            sep='>')

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

Or using just the column position:

In [54]:
pd.read_csv('exam_review.csv',
            usecols=[0, 1, 4],
            sep='>')

  first_name last_name french_score
0        Ray    Morley       75,000
1     Melvin     Scott           83
2     Amirah     Haley           67
3     Gerard     Mills           72
4        Amy    Grimes           81

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Using a `Series` instead of `DataFrame`

If the parsed data only contains one column then we can return a Series by setting the `squeeze` parameter to `True`.

In [ ]:
exam_test_1 = pd.read_csv('exam_review.csv',
                          sep='>',
                          usecols=['last_name'])

In [ ]:
type(exam_test_1)

pandas.core.frame.DataFrame

In [ ]:
exam_test_2 = pd.read_csv('exam_review.csv',
                          sep='>',
                          usecols=['last_name'],
                          squeeze=True)

In [ ]:
type(exam_test_2)

pandas.core.series.Series

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Save to CSV file

Finally we can also save our `DataFrame` as a CSV file.

In [ ]:
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

We can simply generate a CSV string from our `DataFrame`:

In [55]:
exam_df.to_csv()

',first_name,last_name,age,math_score,french_score\n0,Ray,Morley,18,"68,000","75,000"\n1,Melvin,Scott,24,77,83\n2,Amirah,Haley,22,92,67\n3,Gerard,Mills,19,"78,000",72\n4,Amy,Grimes,23,91,81\n'

Or specify a file path where we want our generated CSV code to be saved:

In [56]:
exam_df.to_csv('out.csv')

In [68]:
pd.read_csv('out.csv', index_col= [1])

            Unnamed: 0 last_name  age math_score french_score
first_name
Ray                  0    Morley   18     68,000       75,000
Melvin               1     Scott   24         77           83
Amirah               2     Haley   22         92           67
Gerard               3     Mills   19     78,000           72
Amy                  4    Grimes   23         91           81

In [71]:
exam_df.to_csv('out.csv',
               index = None)

In [72]:
pd.read_csv('out.csv')

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)