![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [83]:
!pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.1.0)

In [84]:
import pandas as pd

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Parsing raw HTML strings

Another useful pandas method is `read_html()`. This method will read HTML tables from a given URL, a file-like object, or a raw string containing HTML, and return a list of `DataFrame` objects.

Let's try to read the following `html_string` into a `DataFrame`.

In [85]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th>
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td>
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td>
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td>
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td>
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [86]:
dfs = pd.read_html(html_string)

/tmp/ipykernel_33667/2234146965.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  dfs = pd.read_html(html_string)

The `read_html` just returned one `DataFrame` object:

In [87]:
len(dfs)

1

In [88]:
df = dfs[0]

df

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

Previous `DataFrame` looks quite similar to the raw HTML table, but now we have a `DataFrame` object, so we can apply any pandas operation we want to it.

In [89]:
df.shape

(4, 5)

In [90]:
df.loc[df['Region'] == 'Central']

  Order date   Region    Item  Units  Unit cost
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [91]:
df.loc[df['Units'] > 35]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

### Defining header

Pandas will automatically find the header to use thanks to the <thead> tag.
    
But in many cases we'll find wrong or incomplete tables that make the `read_html` method parse the tables in a wrong way without the proper headers.

To fix them we can use the `header` parameter.

In [92]:
html_string = """
<table>
  <tr>
    <td>Order date</td>
    <td>Region</td>
    <td>Item</td>
    <td>Units</td>
    <td>Unit cost</td>
  </tr>
  <tr>
    <td>1/6/2018</td>
    <td>East</td>
    <td>Pencil</td>
    <td>95</td>
    <td>1.99</td>
  </tr>
  <tr>
    <td>1/23/2018</td>
    <td>Central</td>
    <td>Binder</td>
    <td>50</td>
    <td>19.99</td>
  </tr>
  <tr>
    <td>2/9/2018</td>
    <td>Central</td>
    <td>Pencil</td>
    <td>36</td>
    <td>4.99</td>
  </tr>
  <tr>
    <td>3/15/2018</td>
    <td>West</td>
    <td>Pen</td>
    <td>27</td>
    <td>19.99</td>
  </tr>
</table>
"""

In [93]:
pd.read_html(html_string)[0]

/tmp/ipykernel_33667/2877898795.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html_string)[0]

            0        1       2      3          4
0  Order date   Region    Item  Units  Unit cost
1    1/6/2018     East  Pencil     95       1.99
2   1/23/2018  Central  Binder     50      19.99
3    2/9/2018  Central  Pencil     36       4.99
4   3/15/2018     West     Pen     27      19.99

In this case, we'll need to pass the row number to use as header using the `header` parameter.

In [94]:
pd.read_html(html_string, header=0)[0]

/tmp/ipykernel_33667/3156000096.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_html(html_string, header=0)[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Parsing HTML tables from the web

Now that we know how `read_html` works, go one step beyond and try to parse HTML tables directly from an URL.

To do that we'll call the `read_html` method with an URL as paramter.

### Simple example

In [95]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

In [96]:
nba_tables = pd.read_html(html_url)

In [ ]:
len(nba_tables)

1

We'll work with the only one table found:

In [97]:
nba = nba_tables[0]

In [98]:
nba.head()

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,James Harden,29.0,HOU,PG,78.0,78.0,36.8,10.8,24.5,...,0.8,5.8,6.6,7.5,2.0,0.7,5.0,3.1,36.1,"MVP-2,AS,NBA1"
1,2.0,Paul George,28.0,OKC,SF,77.0,77.0,36.9,9.2,21.0,...,1.4,6.8,8.2,4.1,2.2,0.4,2.7,2.8,28.0,"MVP-3,DPOY-3,AS,NBA1,DEF1"
2,3.0,Giannis Antetokounmpo,24.0,MIL,PF,72.0,72.0,32.8,10.0,17.3,...,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7,"MVP-1,DPOY-2,AS,NBA1,DEF1"
3,4.0,Joel Embiid,24.0,PHI,C,64.0,64.0,33.7,9.1,18.7,...,2.5,11.1,13.6,3.7,0.7,1.9,3.5,3.3,27.5,"MVP-7,DPOY-4,AS,NBA2,DEF2"
4,5.0,LeBron James,34.0,LAL,SF,55.0,55.0,35.2,10.1,19.9,...,1.0,7.4,8.5,8.3,1.3,0.6,3.6,1.7,27.4,"MVP-11,AS,NBA3"

### Complex example

We can also use the `requests` module to get HTML code from an URL to parse it into `DataFrame` objects.

If we look at the given URL we can see multiple tables about The Simpsons TV show.

We want to keep the table with information about each season.

In [143]:
import requests

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"

In [144]:
my_headers = {
    'User-Agent': 'DataScienceProject/1.0 (contact@email.com)',
    'Accept-Language': 'en-US'
}
r = requests.get(html_url, headers = my_headers)

wiki_tables = pd.read_html(r.text, header=0)
wiki_tables[2]

/tmp/ipykernel_33667/2909979738.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  wiki_tables = pd.read_html(r.text, header=0)

,Season,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Most watched episode,Most watched episode
1,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Viewers (millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][165],33.5[166],"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[167],"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[168],"""Colonel Homer"""
5,4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][169],28.6[170],"""Lisa's First Word"""
6,5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[171],"""Treehouse of Horror IV"""
7,6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,9m h.[n1][172],22.2[173],"""Treehouse of Horror V"""
8,7,1995–96,25,"September 17, 1995","May 19, 1996",Sunday 8:00 pm (Episodes 1–24) Sunday 8:30 pm ...,8m h.[n1][174],22.6[175],"""Who Shot Mr. Burns? – Part II"""
9,8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3) Sunday 8:00 pm (...,8.6m h.[177],20.41[178],"""The Springfield Files"""
10,9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,9.1m h.[179],19.80[180],"""The Two Mrs. Nahasapeemapetilons"""
11,10,1998–99,23,"August 23, 1998","May 16, 1999",Sunday 8:00 pm,7.9m h.[181],19.11[182],"""Sunday, Cruddy Sunday"""
12,11,1999–2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00 pm,8.2m h.[183],19.16[184],"""Faith Off"""
13,12,2000–01,21,"November 1, 2000","May 20, 2001",Sunday 8:00 pm,14.7m v.[185],18.52[186],"""HOMR"""
14,13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1) Sunday 8:00 pm (Ep...,12.4m v.[187],14.91[188],"""The Parent Rap"""
15,14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21) Sunday 8...",13.4m v.[189],22.04[190],"""I'm Spelling as Fast as I Can"""
16,15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,10.6m v.[191],16.30[192],"""I, (Annoyed Grunt)-Bot"""
17,16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20) Su...",9.6m v.[193],23.07[194],"""Homer and Ned's Hail Mary Pass"""
18,17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.1m v.[195],11.66[196],"""Treehouse of Horror XVI"""
19,18,2006–07,22,"September 10, 2006","May 20, 2007",Sunday 8:00 pm,8.6m v.[197],11.63[198],"""The Mook, the Chef, the Wife and Her Homer"""
20,19,2007–08,20,"September 23, 2007","May 18, 2008",Sunday 8:00 pm,8m v.[199],11.74[200],"""Treehouse of Horror XVIII"""
21,20,2008–09,21,"September 28, 2008","May 17, 2009","Sunday 8:00 pm (Episodes 1–7, 9–21) Sunday 8:3...",6.9m v.[201],12.40[202],"""Treehouse of Horror XIX"""
22,21,2009–10,23,"September 27, 2009","May 23, 2010",Sunday 8:00 pm,7.2m v.[203],14.62[204],"""Once Upon a Time in Springfield"""
23,22,2010–11,22,"September 26, 2010","May 22, 2011",Sunday 8:00 pm,7.3m v.[205],12.55[206],"""Moms I'd Like to Forget"""
24,23,2011–12,22,"September 25, 2011","May 20, 2012",Sunday 8:00 pm,7m v.[207],11.48[208],"""The D'oh-cial Network"""
25,24,2012–13,22,"September 30, 2012","May 19, 2013",Sunday 8:00 pm (Episodes 1–21) Sunday 8:30 pm ...,6.3m v.[209],8.97[210],"""Homer Goes to Prep School"""
26,25,2013–14,22,"September 29, 2013","May 18, 2014","Sunday 8:00 pm (Episodes 1–11, 13–22) Sunday 7...",5.6m v.[211],12.04[212],"""Steal This Episode"""
27,26,2014–15,22,"September 28, 2014","May 17, 2015",Sunday 8:00 pm,5.6m v.[213],10.62[214],"""The Man Who Came to Be Dinner"""
28,27,2015–16,22,"September 27, 2015","May 22, 2016",Sunday 8:00 pm,4.7m v.[215],8.33[216],"""Teenage Mutant Milk-Caused Hurdles"""
29,28,2016–17,22,"September 25, 2016","May 21, 2017",Sunday 8:00 pm,4.8[217],8.19[218],"""Pork and Burns"""
30,29,2017–18,21,"October 1, 2017","May 20, 2018",Sunday 8:00 pm,4.1m v.[219],8.04[220],"""Frink Gets Testy"""
31,30,2018–19,23,"September 30, 2018","May 12, 2019",Sunday 8:00 pm,3.7m v.[221],8.20[222],"""The Girl on the Bus"""
32,31,2019–20,22,"September 29, 2019","May 17, 2020",Sunday 8:00 pm,3m v.[223],5.63[224],"""Go Big or Go Homer"""
33,32,2020–21,22,"September 27, 2020","May 23, 2021","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.4m v.[225],4.93[226],"""Treehouse of Horror XXXI"""
34,33,2021–22,22,"September 26, 2021","May 22, 2022","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.3m v.[227],3.97[228],"""Portrait of a Lackey on Fire"""
35,34,2022–23,22,"September 25, 2022","May 21, 2023","Sunday 8:00 pm (Episodes 1–8, 10–22) Sunday 8:...",2.1m v.[229],4.77[230],"""From Beer to Paternity"""
36,35,2023–24,18,"October 1, 2023","May 19, 2024","Sunday 8:00 pm (Episodes 1–5, 7, 10–18) Sunday...",1.99m v.[231],5.41[232],"""Do the Wrong Thing"""
37,36,2024–25,22,"September 29, 2024","May 18, 2025","Sunday 8:00 pm (Episodes 1–2, 4–7, 10–18) Sund...",NaN,3.31[233],"""Bottle Episode"""
38,37,2025–26,17,"September 28, 2025",TBA,"Sunday 8:00 pm (Episodes 1–5, 7, 9–17)[234] Su...",TBD,4.08[235],"""Treehouse of Horror XXXVI"""

In [145]:
len(wiki_tables)

47

In [146]:
simpsons = wiki_tables[2]

In [147]:
#simpsons.set_index('Season', inplace = True)
simpsons

,Season,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
0,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Most watched episode,Most watched episode
1,Season,Season,No. of episodes,Season premiere,Season finale,Time slot (ET),Avg. households / viewers (in millions),Viewers (millions),Episode title
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][165],33.5[166],"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[167],"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[168],"""Colonel Homer"""
5,4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][169],28.6[170],"""Lisa's First Word"""
6,5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[171],"""Treehouse of Horror IV"""
7,6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,9m h.[n1][172],22.2[173],"""Treehouse of Horror V"""
8,7,1995–96,25,"September 17, 1995","May 19, 1996",Sunday 8:00 pm (Episodes 1–24) Sunday 8:30 pm ...,8m h.[n1][174],22.6[175],"""Who Shot Mr. Burns? – Part II"""
9,8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3) Sunday 8:00 pm (...,8.6m h.[177],20.41[178],"""The Springfield Files"""
10,9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,9.1m h.[179],19.80[180],"""The Two Mrs. Nahasapeemapetilons"""
11,10,1998–99,23,"August 23, 1998","May 16, 1999",Sunday 8:00 pm,7.9m h.[181],19.11[182],"""Sunday, Cruddy Sunday"""
12,11,1999–2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00 pm,8.2m h.[183],19.16[184],"""Faith Off"""
13,12,2000–01,21,"November 1, 2000","May 20, 2001",Sunday 8:00 pm,14.7m v.[185],18.52[186],"""HOMR"""
14,13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1) Sunday 8:00 pm (Ep...,12.4m v.[187],14.91[188],"""The Parent Rap"""
15,14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21) Sunday 8...",13.4m v.[189],22.04[190],"""I'm Spelling as Fast as I Can"""
16,15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,10.6m v.[191],16.30[192],"""I, (Annoyed Grunt)-Bot"""
17,16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20) Su...",9.6m v.[193],23.07[194],"""Homer and Ned's Hail Mary Pass"""
18,17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.1m v.[195],11.66[196],"""Treehouse of Horror XVI"""
19,18,2006–07,22,"September 10, 2006","May 20, 2007",Sunday 8:00 pm,8.6m v.[197],11.63[198],"""The Mook, the Chef, the Wife and Her Homer"""
20,19,2007–08,20,"September 23, 2007","May 18, 2008",Sunday 8:00 pm,8m v.[199],11.74[200],"""Treehouse of Horror XVIII"""
21,20,2008–09,21,"September 28, 2008","May 17, 2009","Sunday 8:00 pm (Episodes 1–7, 9–21) Sunday 8:3...",6.9m v.[201],12.40[202],"""Treehouse of Horror XIX"""
22,21,2009–10,23,"September 27, 2009","May 23, 2010",Sunday 8:00 pm,7.2m v.[203],14.62[204],"""Once Upon a Time in Springfield"""
23,22,2010–11,22,"September 26, 2010","May 22, 2011",Sunday 8:00 pm,7.3m v.[205],12.55[206],"""Moms I'd Like to Forget"""
24,23,2011–12,22,"September 25, 2011","May 20, 2012",Sunday 8:00 pm,7m v.[207],11.48[208],"""The D'oh-cial Network"""
25,24,2012–13,22,"September 30, 2012","May 19, 2013",Sunday 8:00 pm (Episodes 1–21) Sunday 8:30 pm ...,6.3m v.[209],8.97[210],"""Homer Goes to Prep School"""
26,25,2013–14,22,"September 29, 2013","May 18, 2014","Sunday 8:00 pm (Episodes 1–11, 13–22) Sunday 7...",5.6m v.[211],12.04[212],"""Steal This Episode"""
27,26,2014–15,22,"September 28, 2014","May 17, 2015",Sunday 8:00 pm,5.6m v.[213],10.62[214],"""The Man Who Came to Be Dinner"""
28,27,2015–16,22,"September 27, 2015","May 22, 2016",Sunday 8:00 pm,4.7m v.[215],8.33[216],"""Teenage Mutant Milk-Caused Hurdles"""
29,28,2016–17,22,"September 25, 2016","May 21, 2017",Sunday 8:00 pm,4.8[217],8.19[218],"""Pork and Burns"""
30,29,2017–18,21,"October 1, 2017","May 20, 2018",Sunday 8:00 pm,4.1m v.[219],8.04[220],"""Frink Gets Testy"""
31,30,2018–19,23,"September 30, 2018","May 12, 2019",Sunday 8:00 pm,3.7m v.[221],8.20[222],"""The Girl on the Bus"""
32,31,2019–20,22,"September 29, 2019","May 17, 2020",Sunday 8:00 pm,3m v.[223],5.63[224],"""Go Big or Go Homer"""
33,32,2020–21,22,"September 27, 2020","May 23, 2021","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.4m v.[225],4.93[226],"""Treehouse of Horror XXXI"""
34,33,2021–22,22,"September 26, 2021","May 22, 2022","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.3m v.[227],3.97[228],"""Portrait of a Lackey on Fire"""
35,34,2022–23,22,"September 25, 2022","May 21, 2023","Sunday 8:00 pm (Episodes 1–8, 10–22) Sunday 8:...",2.1m v.[229],4.77[230],"""From Beer to Paternity"""
36,35,2023–24,18,"October 1, 2023","May 19, 2024","Sunday 8:00 pm (Episodes 1–5, 7, 10–18) Sunday...",1.99m v.[231],5.41[232],"""Do the Wrong Thing"""
37,36,2024–25,22,"September 29, 2024","May 18, 2025","Sunday 8:00 pm (Episodes 1–2, 4–7, 10–18) Sund...",NaN,3.31[233],"""Bottle Episode"""
38,37,2025–26,17,"September 28, 2025",TBA,"Sunday 8:00 pm (Episodes 1–5, 7, 9–17)[234] Su...",TBD,4.08[235],"""Treehouse of Horror XXXVI"""

Quick clean on the table: remove extra header rows and set `Season` as index.

In [148]:
simpsons.drop([0,1], inplace = True)

In [149]:
simpsons

,Season,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][165],33.5[166],"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[167],"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[168],"""Colonel Homer"""
5,4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][169],28.6[170],"""Lisa's First Word"""
6,5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[171],"""Treehouse of Horror IV"""
7,6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,9m h.[n1][172],22.2[173],"""Treehouse of Horror V"""
8,7,1995–96,25,"September 17, 1995","May 19, 1996",Sunday 8:00 pm (Episodes 1–24) Sunday 8:30 pm ...,8m h.[n1][174],22.6[175],"""Who Shot Mr. Burns? – Part II"""
9,8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3) Sunday 8:00 pm (...,8.6m h.[177],20.41[178],"""The Springfield Files"""
10,9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,9.1m h.[179],19.80[180],"""The Two Mrs. Nahasapeemapetilons"""
11,10,1998–99,23,"August 23, 1998","May 16, 1999",Sunday 8:00 pm,7.9m h.[181],19.11[182],"""Sunday, Cruddy Sunday"""
12,11,1999–2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00 pm,8.2m h.[183],19.16[184],"""Faith Off"""
13,12,2000–01,21,"November 1, 2000","May 20, 2001",Sunday 8:00 pm,14.7m v.[185],18.52[186],"""HOMR"""
14,13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1) Sunday 8:00 pm (Ep...,12.4m v.[187],14.91[188],"""The Parent Rap"""
15,14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21) Sunday 8...",13.4m v.[189],22.04[190],"""I'm Spelling as Fast as I Can"""
16,15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,10.6m v.[191],16.30[192],"""I, (Annoyed Grunt)-Bot"""
17,16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20) Su...",9.6m v.[193],23.07[194],"""Homer and Ned's Hail Mary Pass"""
18,17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.1m v.[195],11.66[196],"""Treehouse of Horror XVI"""
19,18,2006–07,22,"September 10, 2006","May 20, 2007",Sunday 8:00 pm,8.6m v.[197],11.63[198],"""The Mook, the Chef, the Wife and Her Homer"""
20,19,2007–08,20,"September 23, 2007","May 18, 2008",Sunday 8:00 pm,8m v.[199],11.74[200],"""Treehouse of Horror XVIII"""
21,20,2008–09,21,"September 28, 2008","May 17, 2009","Sunday 8:00 pm (Episodes 1–7, 9–21) Sunday 8:3...",6.9m v.[201],12.40[202],"""Treehouse of Horror XIX"""
22,21,2009–10,23,"September 27, 2009","May 23, 2010",Sunday 8:00 pm,7.2m v.[203],14.62[204],"""Once Upon a Time in Springfield"""
23,22,2010–11,22,"September 26, 2010","May 22, 2011",Sunday 8:00 pm,7.3m v.[205],12.55[206],"""Moms I'd Like to Forget"""
24,23,2011–12,22,"September 25, 2011","May 20, 2012",Sunday 8:00 pm,7m v.[207],11.48[208],"""The D'oh-cial Network"""
25,24,2012–13,22,"September 30, 2012","May 19, 2013",Sunday 8:00 pm (Episodes 1–21) Sunday 8:30 pm ...,6.3m v.[209],8.97[210],"""Homer Goes to Prep School"""
26,25,2013–14,22,"September 29, 2013","May 18, 2014","Sunday 8:00 pm (Episodes 1–11, 13–22) Sunday 7...",5.6m v.[211],12.04[212],"""Steal This Episode"""
27,26,2014–15,22,"September 28, 2014","May 17, 2015",Sunday 8:00 pm,5.6m v.[213],10.62[214],"""The Man Who Came to Be Dinner"""
28,27,2015–16,22,"September 27, 2015","May 22, 2016",Sunday 8:00 pm,4.7m v.[215],8.33[216],"""Teenage Mutant Milk-Caused Hurdles"""
29,28,2016–17,22,"September 25, 2016","May 21, 2017",Sunday 8:00 pm,4.8[217],8.19[218],"""Pork and Burns"""
30,29,2017–18,21,"October 1, 2017","May 20, 2018",Sunday 8:00 pm,4.1m v.[219],8.04[220],"""Frink Gets Testy"""
31,30,2018–19,23,"September 30, 2018","May 12, 2019",Sunday 8:00 pm,3.7m v.[221],8.20[222],"""The Girl on the Bus"""
32,31,2019–20,22,"September 29, 2019","May 17, 2020",Sunday 8:00 pm,3m v.[223],5.63[224],"""Go Big or Go Homer"""
33,32,2020–21,22,"September 27, 2020","May 23, 2021","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.4m v.[225],4.93[226],"""Treehouse of Horror XXXI"""
34,33,2021–22,22,"September 26, 2021","May 22, 2022","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.3m v.[227],3.97[228],"""Portrait of a Lackey on Fire"""
35,34,2022–23,22,"September 25, 2022","May 21, 2023","Sunday 8:00 pm (Episodes 1–8, 10–22) Sunday 8:...",2.1m v.[229],4.77[230],"""From Beer to Paternity"""
36,35,2023–24,18,"October 1, 2023","May 19, 2024","Sunday 8:00 pm (Episodes 1–5, 7, 10–18) Sunday...",1.99m v.[231],5.41[232],"""Do the Wrong Thing"""
37,36,2024–25,22,"September 29, 2024","May 18, 2025","Sunday 8:00 pm (Episodes 1–2, 4–7, 10–18) Sund...",NaN,3.31[233],"""Bottle Episode"""
38,37,2025–26,17,"September 28, 2025",TBA,"Sunday 8:00 pm (Episodes 1–5, 7, 9–17)[234] Su...",TBD,4.08[235],"""Treehouse of Horror XXXVI"""

Which season has the lowest number of episodes?

In [151]:
simpsons['No. of episodes'].unique()

array(['13', '22', '24', '25', '23', '21', '20', '18', '17'], dtype=object)

In [153]:
simpsons = simpsons.loc[simpsons['No. of episodes'] != 'TBA']

In [157]:
min_season = simpsons['No. of episodes'].min()
min_season

'13'

In [161]:
simpsons.loc[simpsons['No. of episodes'] != 'min_season']

,Season,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][165],33.5[166],"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[167],"""Bart Gets an 'F'"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[168],"""Colonel Homer"""
5,4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][169],28.6[170],"""Lisa's First Word"""
6,5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[171],"""Treehouse of Horror IV"""
7,6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,9m h.[n1][172],22.2[173],"""Treehouse of Horror V"""
8,7,1995–96,25,"September 17, 1995","May 19, 1996",Sunday 8:00 pm (Episodes 1–24) Sunday 8:30 pm ...,8m h.[n1][174],22.6[175],"""Who Shot Mr. Burns? – Part II"""
9,8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3) Sunday 8:00 pm (...,8.6m h.[177],20.41[178],"""The Springfield Files"""
10,9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,9.1m h.[179],19.80[180],"""The Two Mrs. Nahasapeemapetilons"""
11,10,1998–99,23,"August 23, 1998","May 16, 1999",Sunday 8:00 pm,7.9m h.[181],19.11[182],"""Sunday, Cruddy Sunday"""
12,11,1999–2000,22,"September 26, 1999","May 21, 2000",Sunday 8:00 pm,8.2m h.[183],19.16[184],"""Faith Off"""
13,12,2000–01,21,"November 1, 2000","May 20, 2001",Sunday 8:00 pm,14.7m v.[185],18.52[186],"""HOMR"""
14,13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1) Sunday 8:00 pm (Ep...,12.4m v.[187],14.91[188],"""The Parent Rap"""
15,14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21) Sunday 8...",13.4m v.[189],22.04[190],"""I'm Spelling as Fast as I Can"""
16,15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,10.6m v.[191],16.30[192],"""I, (Annoyed Grunt)-Bot"""
17,16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20) Su...",9.6m v.[193],23.07[194],"""Homer and Ned's Hail Mary Pass"""
18,17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.1m v.[195],11.66[196],"""Treehouse of Horror XVI"""
19,18,2006–07,22,"September 10, 2006","May 20, 2007",Sunday 8:00 pm,8.6m v.[197],11.63[198],"""The Mook, the Chef, the Wife and Her Homer"""
20,19,2007–08,20,"September 23, 2007","May 18, 2008",Sunday 8:00 pm,8m v.[199],11.74[200],"""Treehouse of Horror XVIII"""
21,20,2008–09,21,"September 28, 2008","May 17, 2009","Sunday 8:00 pm (Episodes 1–7, 9–21) Sunday 8:3...",6.9m v.[201],12.40[202],"""Treehouse of Horror XIX"""
22,21,2009–10,23,"September 27, 2009","May 23, 2010",Sunday 8:00 pm,7.2m v.[203],14.62[204],"""Once Upon a Time in Springfield"""
23,22,2010–11,22,"September 26, 2010","May 22, 2011",Sunday 8:00 pm,7.3m v.[205],12.55[206],"""Moms I'd Like to Forget"""
24,23,2011–12,22,"September 25, 2011","May 20, 2012",Sunday 8:00 pm,7m v.[207],11.48[208],"""The D'oh-cial Network"""
25,24,2012–13,22,"September 30, 2012","May 19, 2013",Sunday 8:00 pm (Episodes 1–21) Sunday 8:30 pm ...,6.3m v.[209],8.97[210],"""Homer Goes to Prep School"""
26,25,2013–14,22,"September 29, 2013","May 18, 2014","Sunday 8:00 pm (Episodes 1–11, 13–22) Sunday 7...",5.6m v.[211],12.04[212],"""Steal This Episode"""
27,26,2014–15,22,"September 28, 2014","May 17, 2015",Sunday 8:00 pm,5.6m v.[213],10.62[214],"""The Man Who Came to Be Dinner"""
28,27,2015–16,22,"September 27, 2015","May 22, 2016",Sunday 8:00 pm,4.7m v.[215],8.33[216],"""Teenage Mutant Milk-Caused Hurdles"""
29,28,2016–17,22,"September 25, 2016","May 21, 2017",Sunday 8:00 pm,4.8[217],8.19[218],"""Pork and Burns"""
30,29,2017–18,21,"October 1, 2017","May 20, 2018",Sunday 8:00 pm,4.1m v.[219],8.04[220],"""Frink Gets Testy"""
31,30,2018–19,23,"September 30, 2018","May 12, 2019",Sunday 8:00 pm,3.7m v.[221],8.20[222],"""The Girl on the Bus"""
32,31,2019–20,22,"September 29, 2019","May 17, 2020",Sunday 8:00 pm,3m v.[223],5.63[224],"""Go Big or Go Homer"""
33,32,2020–21,22,"September 27, 2020","May 23, 2021","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.4m v.[225],4.93[226],"""Treehouse of Horror XXXI"""
34,33,2021–22,22,"September 26, 2021","May 22, 2022","Sunday 8:00 pm (Episodes 1–10, 12–22) Sunday 9...",2.3m v.[227],3.97[228],"""Portrait of a Lackey on Fire"""
35,34,2022–23,22,"September 25, 2022","May 21, 2023","Sunday 8:00 pm (Episodes 1–8, 10–22) Sunday 8:...",2.1m v.[229],4.77[230],"""From Beer to Paternity"""
36,35,2023–24,18,"October 1, 2023","May 19, 2024","Sunday 8:00 pm (Episodes 1–5, 7, 10–18) Sunday...",1.99m v.[231],5.41[232],"""Do the Wrong Thing"""
37,36,2024–25,22,"September 29, 2024","May 18, 2025","Sunday 8:00 pm (Episodes 1–2, 4–7, 10–18) Sund...",NaN,3.31[233],"""Bottle Episode"""
38,37,2025–26,17,"September 28, 2025",TBA,"Sunday 8:00 pm (Episodes 1–5, 7, 9–17)[234] Su...",TBD,4.08[235],"""Treehouse of Horror XXXVI"""

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Save to CSV file

Finally save the `DataFrame` to a CSV file as we saw on previous lectures.

In [ ]:
simpsons.head()

,Season.1,No. ofepisodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 PM,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 PM,24.4,33.6,"""Bart Gets an F"""
3,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 PM,21.8,25.5,"""Colonel Homer"""
4,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 PM,22.4,28.6,"""Lisa's First Word"""
5,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 PM,18.9,24.0,"""Treehouse of Horror IV"""

In [167]:
simpsons.to_csv('out.csv')

In [169]:
pd.read_csv('out.csv', index_col='Season').head()

,Unnamed: 0,Season.1,No. of episodes,Originally aired,Originally aired.1,Originally aired.2,Viewership,Viewership.1,Viewership.2
Season,,,,,,,,,
1,2,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,13.4m h.[n1][165],33.5[166],"""Life on the Fast Lane"""
2,3,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,12.2m h.[n1][n2],33.6[167],"""Bart Gets an 'F'"""
3,4,1991–92,24,"September 19, 1991","August 27, 1992",Thursday 8:00 pm,12m h.[n1][n3],25.5[168],"""Colonel Homer"""
4,5,1992–93,22,"September 24, 1992","May 13, 1993",Thursday 8:00 pm,12.1m h.[n1][169],28.6[170],"""Lisa's First Word"""
5,6,1993–94,22,"September 30, 1993","May 19, 1994",Thursday 8:00 pm,10.5m h.[n1][n4],24.0[171],"""Treehouse of Horror IV"""

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)